config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user_signup/", include("user_signup.urls")), 
    path("user_signup/", include("django.contrib.auth.urls")),
    path("", TemplateView.as_view(template_name='home.html'), name='home'),
    path('socially/', include("socially.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = urlpatterns+static(settings.SOCIALLY_URL,
document_root=settings.SOCIALLY_ROOT)

config/socially/urls.py
from django.urls import path
from . import views

app_name = 'socially'
urlpatterns = [
    path('index', views.index, name='index'),
    path('<str:this_user>', views.user_socials, name='user_socials'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('like/<int:pk>', views.likes, name='likes'),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('logout', views.logout, name='logout'),
    path('follow', views.follow, name='follow'),
    path('search', views.search, name='search'),
    path('settings', views.settings, name='settings'),
]

config/socially/models.py
from django.db import models
from django.contrib.auth.models import User

class Action(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    socially = models.ForeignKey('Socially', on_delete=models.CASCADE)
    # comment = models.CharField(max_length=500)
    # comment_time = models.DateTimeField(null=True)
    # shared = models.BooleanField(default=False)
    # shared_time = models.DateTimeField(null=True)
    # saved = models.BooleanField(default=False)

class Socially(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name = 'user')
    interaction = models.ManyToManyField(User, through= Action)
    social_text = models.CharField(max_length=128)
    date_created = models.DateTimeField(auto_now_add = True)
    like = models.ManyToManyField(User, related_name ='likes')
    
    def total_like(self):
        return self.like.count()

    def __str__(self):
        return self.social_text

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id_user = models.IntegerField()
    bio = models.TextField(blank=True)
    location = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.username

class FollowersCount(models.Model):
    follower = models.CharField(max_length=100)
    user = models.CharField(max_length=100)

    def __str__(self):
        return self.user

config/socially/views.py
from django.urls import reverse, reverse
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User, auth
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Profile,  FollowersCount
from itertools import chain
import random
from django.contrib import messages
def index(request):
    context = {}
    if request.method == 'POST':
        if request.user.is_authenticated:
            social_text = request.POST.get('social-text')
            socially_user = request.user
            Socially.objects.create(social_text=social_text, author=socially_user)
        else:
            context['message'] = 'You are not logged in.'
    all_socials = Socially.objects.all()
    def get_context_data(self, *args, **kwargs):
        stuff=get_object_or_404(Socially, id=self.kwargs['pk'])
        total_like = stuff.total_like()
        context["total_like"] = total_like
        return context
    context['all_socials']= all_socials
    return render(request, 'socially/index.html', context)

def user_socials(request, this_user):
    context = {}
    if request.method == 'POST':
        if request.user.is_authenticated:
            social_text = request.POST.get('social-text')
            socially_user = request.user
            Socially.objects.create(social_text=social_text, author=socially_user)
        else:
            context['message'] = 'You are not logged in.'
    this_user = User.objects.get(username=this_user)
    all_socials = Socially.objects.filter(author=this_user)
    context['all_ socials']= all_socials
    return render(request, 'socially/index.html', context)

def delete(request, id):
    social = Socially.objects.get(id = id)
    social.delete()
    return redirect('/socially/index/')

def likes(request, pk):
    print(pk)
    post = get_object_or_404(Socially, id=pk)
    print(post)
    post.like.add(request.user)
    return HttpResponseRedirect(reverse('socially:index'))

@login_required(login_url='signin')
def search(request):
    user_object = User.objects.get(username=request.user.username)
    user_profile = Profile.objects.get(user=user_object)

    if request.method == 'POST':
        username = request.POST['username']
        username_object = User.objects.filter(username__icontains=username)

        username_profile = []
        username_profile_list = []

        for users in username_object:
            username_profile.append(users.id)

        for ids in username_profile:
            profile_lists = Profile.objects.filter(id_user=ids)
            username_profile_list.append(profile_lists)
        
        username_profile_list = list(chain(*username_profile_list))
    return render(request, 'search.html', {'user_profile': user_profile, 'username_profile_list': username_profile_list})
@login_required(login_url='signin')
def profile(request, pk):
    user_object = User.objects.get(username=pk)
    user_profile = Profile.objects.get(user=user_object)
    user_posts = Socially.objects.filter(user=pk)
    user_post_length = len(user_posts)

    follower = request.user.username
    user = pk

    if FollowersCount.objects.filter(follower=follower, user=user).first():
        button_text = 'Unfollow'
    else:
        button_text = 'Follow'

    user_followers = len(FollowersCount.objects.filter(user=pk))
    user_following = len(FollowersCount.objects.filter(follower=pk))

    context = {
        'user_object': user_object,
        'user_profile': user_profile,
        'user_posts': user_posts,
        'user_post_length': user_post_length,
        'button_text': button_text,
        'user_followers': user_followers,
        'user_following': user_following,
    }
    return render(request, 'profile.html', context)

@login_required(login_url='signin')
def follow(request):
    if request.method == 'POST':
        follower = request.POST['follower']
        user = request.POST['user']

        if FollowersCount.objects.filter(follower=follower, user=user).first():
            delete_follower = FollowersCount.objects.get(follower=follower, user=user)
            delete_follower.delete()
            return redirect('/profile/'+user)
        else:
            new_follower = FollowersCount.objects.create(follower=follower, user=user)
            new_follower.save()
            return redirect('/profile/'+user)
    else:
        return redirect('/')

@login_required(login_url='signin')
def settings(request):
    user_profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        
        if request.FILES.get('image') == None:
            bio = request.POST['bio']
            location = request.POST['location']

            user_profile.bio = bio
            user_profile.location = location
            user_profile.save()
        if request.FILES.get('image') != None:
            bio = request.POST['bio']
            location = request.POST['location']

            user_profile.bio = bio
            user_profile.location = location
            user_profile.save()
        
        return redirect('settings')
    return render(request, 'setting.html', {'user_profile': user_profile})

def signup(request):

    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        if password == password2:
            if User.objects.filter(email=email).exists():
                messages.info(request, 'Email Taken')
                return redirect('signup')
            elif User.objects.filter(username=username).exists():
                messages.info(request, 'Username Taken')
                return redirect('signup')
            else:
                user = User.objects.create_user(username=username, email=email, password=password)
                user.save()

                #log user in and redirect to settings page
                user_login = auth.authenticate(username=username, password=password)
                auth.login(request, user_login)

                #create a Profile object for the new user
                user_model = User.objects.get(username=username)
                new_profile = Profile.objects.create(user=user_model, id_user=user_model.id)
                new_profile.save()
                return redirect('settings')
        else:
            messages.info(request, 'Password Not Matching')
            return redirect('signup')
        
    else:
        return render(request, 'signup.html')

def signin(request):
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Credentials Invalid')
            return redirect('signin')

    else:
        return render(request, 'signin.html')

@login_required(login_url='signin')
def logout(request):
    auth.logout(request)
    return redirect('signin')

config/socially/templates/socially/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Socially</title>
<script src="{% static 'javascript/app.js' %}" defer></script>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Socially</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="http://localhost:8000/socially/index/">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
            </li>
        </ul>
        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        </div>
    </div>
    </nav>
    <br><br><br><br>
<div id="container">
<article>

    <header>
        <h1 id="welcome">
        Welcome to Socially!
        </h1>
    </header>
</article>
    <form action="{% url 'socially:index' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="social-text">
        <button type="button submit" class="btn btn-outline-success">Post Social</button>
    </form>
    {% for social in all_socials reversed%}
    <br>
    <div class="card" style="width: 18rem;">
        <div class="card-body shadow-lg">
            <h5 class="card-title">{{ social.author}}</h5>
            <p class="card-text">{{ social.social_text}}</p>
            <form action="{% url 'socially:likes' social.pk %}" method="POST"> 
                {% csrf_token %}
                {% if user == social.author %}
                <a class="btn btn-success" href="{% url 'socially:delete' social.id %}" role="button">Delete</a>
                {% endif %}
                <button type="submit" value="{{ social.pk}}" class="btn btn-success position-relative">Likes<span class="amazing position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                        {{social.total_like}}
                        <span class="visually-hidden">unread messages</span>
                    </span>
                </button>
            </form>
            <div class="card-footer">
                <p class="card-text"><small class="text-muted">{{social.date_created}}</small></p>
        </div>
        </div>
    </div>
    {% endfor %}
    <div id="easter" style="display: none;">
        <img src="{% static 'images/.jpg' %}" alt="">
    </div>
    <div id="egg">
        open
    </div>
</div>

    </body>
    <!-- footer -->
    <footer id="footer"class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-muted">© 2022 Socially, Inc</p>
    
        <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none position-absolute bottom-0 middle-0">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        </a>
    
        <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
        </ul>
    </footer>

</body>
</html>