config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user_signup/", include("user_signup.urls")), 
    path("user_signup/", include("django.contrib.auth.urls")),
    path("", TemplateView.as_view(template_name='home.html'), name='home'),
    path('socially/', include("socially.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = urlpatterns+static(settings.SOCIALLY_URL,
document_root=settings.SOCIALLY_ROOT)

config/socially/urls.py
from django.urls import path
from . import views

app_name = 'socially'
urlpatterns = [
    path('index', views.index, name='index'),
    path('<str:this_user>', views.user_socials, name='user_socials'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('like/<int:pk>', views.likes, name='likes'),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('logout', views.logout, name='logout'),
    path('follow', views.follow, name='follow'),
    path('search', views.search, name='search'),
    path('settings', views.settings, name='settings'),
]

config/user_signup/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

config/user_signup/models.py
from django.db import models
from django.contrib.auth.models import User

class Friendship (models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friend1_set')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friend2_set')
    created = models.DateTimeField(auto_now_add= True)

config/user_signup/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

config/user_signup/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body id="base">
    <nav class="navbar navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
        <a class="navbar-brand" href="#">Socially</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Tool Kit</h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="http://localhost:8000/user_signup/signup">Sign up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="http://localhost:8000/user_signup/login">Login</a>
                    </li>
            </ul>
            </div>
        </div>
        <div>
    </nav>
<br><br>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Socially</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="http://localhost:8000/user_signup/signup">Signup</a>
            </li>
            <li class="nav-item">
            <a class="nav-link active" href="http://localhost:8000/user_signup/login">Login</a>
            </li>
        </ul>
        </div>
    </div>
    </nav>
    <main id="signup">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

config/user_signup/templates/home.html
{% extends 'base.html' %}
{%load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title>Socially</title>
    </head>
    <body>
        
    
    {% block title %}Home{% endblock %}
    
    {% block content %}
    <!-- hmmmm -->
        {{message}}
    <article>
        <header>
            <h1>
            Thanks for stopping by! We hope to see you soon!
            </h1>
        </header>
    
    {% if user.is_authenticated %}
    <form action="{% url 'socially:index' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="social-text">
        <button id="home" type="submit">Post Social</button>
    </form>

    Please click the link below to be logged out! 
    <p><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
    <p>You have been successfully logged out.</p>
    <a href="{% url 'login' %}">Click me to go back home!</a>
    {% endif %}
    {% endblock %}
</body>
</html>